routes/web.php
    $manager_role->name = 'Super Admim';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'usuario-normal';
    $manager_role->name = 'Usuário normal ';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'gestor-administracao';
    $manager_role->name = 'Gestor Administrativo';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'gestor-manutencao';
    $manager_role->name = 'Gestor da área de manutenção ';
    $manager_role->save();

    $motorista_role = new Role();
    $motorista_role->slug = 'motorista';
    $motorista_role->name = 'Motorista';
    $motorista_role->save();

    $recursos_role = Role::where('slug', 'gestor-recursos-humanos')->first();
    $gestor_administracao_role = Role::where('slug', 'gestor-administracao')->first();
    $usuario_normal_role = Role::where('slug', 'usuario-normal')->first();
    $super_admin_role = Role::where('slug', 'super-admin')->first();
    $manutencao_role = Role::where('slug', 'gestor-manutencao')->first();

    $super_usuario = new User();
    $super_usuario->name = 'Super Usuario';
    $super_usuario->email = 'manager@teste.com';
    $super_usuario->username = 'manage.com';
    $super_usuario->password = bcrypt('manager');
    $super_usuario->save();
    $super_usuario->roles()->attach($super_admin_role);

    $sector = new Sector();
    $sector->user_id = $super_usuario->id;
    $sector->name = "Geral";
    $sector->save();
    $super_usuario->sectors()->attach($sector);

    $administracao = new User();
    $administracao->name = 'Administracao';
    $administracao->email = 'administracao@teste.com';
    $administracao->username = 'administracao.com';
    $administracao->password = bcrypt('administracao');
    $administracao->save();
    $administracao->roles()->attach($gestor_administracao_role);

    $usuario_normal = new User();
    $usuario_normal->name = 'Usuario Normal';
    $usuario_normal->email = 'usuario@teste.com';
    $usuario_normal->username = 'usuario.com';
    $usuario_normal->password = Hash::make(123456);
    $usuario_normal->save();
    $usuario_normal->roles()->attach($usuario_normal_role);

    $recursosH = new User();
    $recursosH->name = 'Recursos H';
    $recursosH->email = 'recursosh@teste.com';
    $recursosH->username = 'recursosh.com';
    $recursosH->password = Hash::make(123456);
    $recursosH->save();
    $recursosH->roles()->attach($recursos_role);

    $manutencao = new User();
    $manutencao->name = 'Manutencao';
    $manutencao->email = 'manutencao@teste.com';
    $manutencao->username = 'manutencao.com';
    $manutencao->password = Hash::make(123456);
    $manutencao->save();
    $manutencao->roles()->attach($manutencao_role);

    return User::all();

});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', function () {
        auth()->logout();
        Session()->flush();
        return Redirect::to('/');
    })->name('logout');

    Route::get('/', 'HomeController@index')->name('normal.dashboard');
    Route::resource('avaria', 'AvariaController');
    Route::resource('escala', 'EscalaController');
    Route::resource('remuneracao', 'AumentoRemuneracaoController');
    Route::resource('justificacao', 'JustificaoFaltaController');
    Route::resource('prolongamento', 'ProlongamentoController');
    Route::resource('pedido', 'PedidoController');
    Route::resource('pedidoRescisao', 'PedidoRescisaoController');
    Route::get('avaria/{avaria}/resposta/detalhes', 'AvariaController@showResponse')->name('avaria.resposta-detalhes');
    Route::get('avaria/{avaria}/pdf/', 'AvariaController@exportAvariaPdf')->name('avaria.export');
    Route::resource('requisicaoTransporte', 'RequisicaoTransporteController');
    Route::get('carta/create', 'CartaController@create')->name('carta.create');

    Route::resource('advertencia', 'AdvertenciaController');
    Route::get('advertencia/geraPDF/{advertencia}', 'AdvertenciaController@makePDF')->name('advertencia.PDF');

    Route::put('avaria/{avaria}/responder', 'AvariaController@responderSolicitacao')->name('avaria.response');

    Route::put('avaria/{avaria}/feedback', 'AvariaController@feedback')->name('avaria.feedback');

    Route::put('avaria/{avaria}/estado', 'AvariaController@setEstado')->name('avaria.estado');

    Route::post('/fecth/dependent', 'RequisicaoTransporteController@selectViagem')->name('requisicao.selectViagem');

    Route::get('/substituicao', 'FeriaController@substituicoes')->name('feria.subistacao');

    Route::get('avaria/geraPDF/{avaria}', 'AvariaController@geraPDF')->name('avaria-requisicao.geraPDF');

    Route::get('pre_requisicao/PDF/{pre}', 'RequisicaoTransporteController@exportPreReqPdf')->name('pre-requisicao.PDF');

    Route::resource('preRequest', 'PreRequisicaoController');
    Route::get('preRequest/{pre}/read', 'PreRequisicaoController@read')->name('pre.read');

    Route::get('user/details/{user}', 'UserRegisterController@show')->name('user.details');
    Route::put('password/update', 'UserRegisterController@updatePassword')->name('password.update');

    Route::post('getSector', 'SectorController@getSector')->name('sector.getSector');
    Route::post('getUser', 'UserRegisterController@getUser')->name('user.getUser');
    Route::post('getTecnico', 'TecnicoController@getTecnico')->name('tecnico.getTecnico');
    Route::post('getMotorista', 'MotoristaController@getMotorista')->name('motorista.getMotorista');
    Route::post('getTransporte', 'TransporteController@getTransporte')->name('transporte.getTransporte');
    Route::resource('rescisao', 'RescisaoController');
    Route::resource('feria', 'FeriaController');
    Route::post('carta/store', 'CartaController@store')->name('carta.store');
    Route::get('carta', 'CartaController@index')->name('carta.index');
    Route::get('chefe/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer.chefe');

});

//Manutencao
Route::group(['middleware' => 'role:gestor-manutencao'], function () {
    Route::resource('tecnico', 'TecnicoController');
    Route::resource('fornecedor', 'FornecedorController');
    Route::post('getFornecedor', 'FornecedorController@getFornecedor');
    Route::get('avaria/{avaria}/descricao', 'AvariaController@showAvariaRequest')->name('avaria.descricao');
    Route::get('avarias/todas', 'AvariaController@todasAvarias')->name('avaria.todas');
    Route::get('avarias/report', 'AvariaController@report')->name('avaria.report');
});

//Manutencao
Route::group(['middleware' => 'role:motorista'], function () {
    Route::resource('tarefa', 'TarefaController');
});

// Administrativo
Route::group(['middleware' => 'role:gestor-administracao'], function () {
    Route::resource('transportes', 'TransporteController');
    Route::resource('local', 'LocalController');
    Route::resource('motorista', 'MotoristaController');
    Route::get('requisicoes', 'RequisicaoTransporteController@allRequests')->name('requisicaoTransporte.all');

    Route::get('requisicoes/report', 'RequisicaoTransporteController@report')->name('requisicoes.report');

    Route::get('requisicao/pdf/{pre}', 'RequisicaoTransporteController@gerarPDF')->name('requisicao.export');
});

//Recursos Humanos
Route::group(['middleware' => 'role:gestor-recursos-humanos'], function () {
    Route::get('cartas/search', 'CartaController@search');
    Route::resource('contrato', 'ContratoController');
    Route::resource('adenda', 'AdendaController');
    Route::get('rechumanos/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer');
    Route::get('adenda/{adenda}/pdf', 'AdendaController@makePDF')->name('adenda.pdf');
    Route::get('contratos/search', 'ContratoController@search');
    Route::get('contratos/{contrato}/pdf', 'ContratoController@makePDFIndividual')->name('contrato.pdfNormal');
    Route::get('prolongamento/{contrato}/pdf', 'ProlongamentoController@makePDF')->name('prolongamento.pdf');
    Route::get('escala/{escala}/pdf', 'EscalaController@makePDF')->name('escala.pdf');
    Route::get('contrato/create/cps', 'ContratoController@createCps')->name('contrato.createCps');
    Route::get('prolongamentos/all', 'ProlongamentoController@todosProlongamentos')->name('prolongamento.all');
    Route::get('ferias/all', 'FeriaController@todasFerias')->name('feria.all');
    Route::get('justificacoes/all', 'JustificaoFaltaController@todasJustificacoes')->name('justificacao.all');

    Route::get('advertencias/all', 'AdvertenciaController@all')->name('advertencia.all');


    Route::get('escalas/all', 'EscalaController@todasEscalas')->name('escala.all');
    Route::get('remuneracoes/all', 'AumentoRemuneracaoController@todas')->name('remuneracao.all');
    Route::get('contratos/all', 'ContratoController@todos')->name('contrato.all');
    Route::get('pedidosRescisao/all', 'PedidoRescisaoController@todos')->name('pedidoRescisao.all');

    Route::get('contrato/{id}/user', 'ContratoController@contratoPeloUsuario')->name('contrato.user');

    Route::get('escalas/report', 'EscalaController@report')->name('escala.report');
    Route::get('pedidosRescisao/report', 'PedidoRescisaoController@report')->name('pedidoRescisao.report');

    Route::get('prolongamentos/report', 'ProlongamentoController@report')->name('prolongamento.report');

    Route::get('justificacoes/report', 'JustificaoFaltaController@report')->name('prolongamento.report');

    Route::get('remuneracoes/report', 'AumentoRemuneracaoController@report')->name('remuneracoes.report');


});

Route::group(['middleware' => 'super-admin'], function () {

    Route::get('/registar', 'UserRegisterController@registerForm')->name('user.register');
    Route::post('/registar', 'UserRegisterController@create')->name('user.gravar');
    Route::resource('sector', 'SectorController');
    Route::get('/usuarios', 'UserRegisterController@index')->name('user.all');

app/Prolongamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prolongamento extends Model
{
    protected $fillable = [
        'tipo_colaborador', 'tipo_escala',
        'pedido_de', 'forma_compensacao', 'motivo', 'user_id', 'sector_id',
    ];

    public $incrementing = false;


    public function dados()
    {
        return $this->hasOne(DadosProlongamento::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function sector()
    {
        return $this->belongsTo(Sector::class);
    }
}

resources/views/prolongamento/all.blade.php
@extends('layouts.admin')

@section('title-page')
    Encontre prolongamentos
@endsection
@section('links')
    <a class="uk-button uk-button-text" href="{{route('prolongamento.index')}}">Prolongamentos</a> / Relatorio
@endsection
@section('link')
    Encontre prolongamentos
@endsection
@section('content-main')
    <div class="conntainer">
        @include('layouts.flash')

        <div class="uk-width-1-1@s uk-padding-small uk-grid">

            <div class="uk-width-1-4@s">
                <label for="data_search" class="uk-form-label">Data inicial</label>
                <input class="uk-input" id="data_search" name="data_inicial" data-uk-datepicker="{format:'DD.MM.YYYY'}"
                    placeholder="Data inicial  (Ano/mm/dd)" autocomplete="off" />
            </div>

            <div class="uk-width-1-4@s">
                <label for="data_search_two" class="uk-form-label">Data final</label>
                <input class="uk-input" id="data_search_two" name="data_final" data-uk-datepicker="{format:'DD.MM.YYYY'}"
                    placeholder="Data final  (Ano/mm/dd)" autocomplete="off" />
            </div>

            <div class="uk-width-1-4@s">
                <label for="sector_id" class="uk-form-label">Sector</label>
                <input class="uk-input" id="sector_search" placeholder="Sector" />
                <input hidden name="sector" id="sector_id" />

            </div>

            <div class="uk-width-1-4@s">
                <label for="user_id" class="uk-form-label">Usuário</label>
                <input id="user_search" class="uk-input" placeholder="Nome do usuário">
                <input hidden name="user" id="user_id" class="uk-input" placeholder="Nome do usuário">
            </div>

            <div class="uk-width-1-4@s uk-margin-top">
                <button id="btn_report_prolongamentos"
                    class="uk-button uk-text-normal uk-button-danger uk-box-shadow-hover-large uk-border-rounded">
                    <span><img width="20px" src="{{  url("storage/icons/pdf.svg") }}"></span>
                    Emitir relatório
                </button>
            </div>

            <div class="uk-width-1-4@s uk-margin-top">
                <button id="reset"
                    class="uk-button uk-text-normal uk-button-secondary uk-box-shadow-hover-large uk-border-rounded">
                    Limpar campos
                </button>
            </div>

        </div>

        <div class="uk-section uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
            @if(!$prolongamentos->isEmpty())
            <div class="uk-card uk-card-default uk-width-1-1@s">
                <div class="uk-overflow-auto">
                    <table id="avarias-tb" class="uk-table uk-table-hover uk-table-responsive uk-table-middle uk-table-divider">
                        <thead>
                            <tr>
                                <th id="table-header" class="uk-width-small">Referência</th>
                                <th id="table-header" class="uk-width-small">Requisitante</th>
                                <th id="table-header" class="uk-width-small">Sector</th>

                                <th id="table-header" class="uk-width-small">Data</th>
                                <th id="table-header" class="uk-table-shrink uk-text-nowrap">Hora do início</th>
                                <th id="table-header" class="uk-table-shrink uk-text-nowrap">Data da submissão</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($prolongamentos as $prolongamento)
                            <tr class="uk-background-muted uk-table-link">
                                <td class="uk-text-bold uk-table-link uk-text-normal">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ $prolongamento->id }}
                                    </a>
                                </td>
                                <td class="uk-text-bold uk-table-link uk-text-normal">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ $prolongamento->user->name }}
                                    </a>
                                </td>

                                <td class="uk-text-normal uk-table-link">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ $prolongamento->sector->name }}
                                    </a>
                                </td>

                                <td class="uk-table-link uk-text-normal">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ date('d/m/Y', strtotime($prolongamento->dados->data_prolongamento)) }}
                                    </a>
                                </td>
                                <td class="uk-text-nowrap uk-table-link uk-text-normal">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ date('H:i', strtotime($prolongamento->dados->hora_inicio_prolongamento)) }}
                                    </a>
                                </td>

                                <td class="uk-table-link uk-text-normal">
                                    <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                        {{ date('d/m/Y', strtotime($prolongamento->created_at)) }}
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            @else
            @include('layouts.empty')
            @endif
        </div>
    </div>
    @component('layouts.alertDate')
    @endcomponent
@endsection

resources/views/prolongamento/create.blade.php
@extends('forms.create-escala-prolongamento')

@section('title-p')
Prolongamento
@endsection

@section('lnk')
    Prolongamento
@endsection
@section('lnks')
<a href="{{ route('prolongamento.index') }}" class="uk-button uk-button-text">Prolongamentos</a> / Emitir
@endsection
@section('action')
    {{ route('prolongamento.store') }}
@endsection
@section('card-title')
Carta de prolongamento
@endsection
@section('tipo_escala')
    <label class="uk-text-small">
        Prolongamento de turno
        <input class="uk-radio" checked value="Prolongamento de turno" type="radio" name="tipo_escala">
    </label>

@endsection
@section('prolongamento')
<div class="table-responsive uk-margin-top">
    <table class="table" id="dynamic_prolongamento">
        <thead>
            <tr>
                <th class="uk-text-small" colspan="4">Dados do prolongamento</th>

            </tr>
            <tr>
                <th class="uk-text-small">Data</th>
                <th class="uk-text-small">Hora de início</th>
                <th class="uk-text-small">Hora de fim</th>
            </tr>
        </thead>
        <tr>
            <td><input name="data_prolongamento[0]" type="date" value="" placeholder="Data"
                    class="uk-input name_list" /></td>
            <td><input type="text" name="hora_inicio_prolongamento[0]" value="" placeholder="HH:mm"
                    class="hora_justificacao uk-input name_list" /></td>
            <td><input name="hora_fim_prolongamento[0]" value="" placeholder="HH:mm"
                    class="uk-input hora_justificacao" /></td>

        </tr>
    </table>
    <td>
        <button type="button" name="add-justificacao" id="add-justificacao"
            class="btn btn-dark uk-box-shadow-hover-medium"><span><i class="fa fa-plus-circle"
                    aria-hidden="true"></i></span>
        </button>
    </td>
</div>
@endsection

resources/views/prolongamento/data-export.blade.php
@extends('layouts.admin')
@section('title-page')
    Pré relatório de pedido de prolongamento
@endsection
@section('links')
    <a class="uk-button uk-button-text"
       href="{{route('prolongamento.all')}}">Requisções</a> / Relatório
@endsection
@section('link')
    Pré relatório de pedido de prolongamento
@endsection
@section('content-main')

    <div class="conntainer">
        @include('layouts.flash')
        <div class="uk-align-right uk-margin-large-right uk-margin-remove-bottom">

        </div>
        <div class="uk-section uk-padding-small uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
            @if(!$prolongamentos->isEmpty())
                <div class="uk-card uk-card-default uk-width-1-1@s">
                    <div class="uk-overflow-auto">
                        <table id="tableDatatableProlongamentos" class="uk-table uk-table-hover uk-table-responsive uk-table-middle uk-table-divider">
                            <thead>
                                <tr>
                                    <th id="table-header" class="uk-width-small">Referência</th>
                                    <th id="table-header" class="uk-width-small">Requisitante</th>
                                    <th id="table-header" class="uk-width-small">Sector</th>

                                    <th id="table-header" class="uk-width-small">Data</th>
                                    <th id="table-header" class="uk-table-shrink uk-text-nowrap">Hora do início</th>
                                    <th id="table-header" class="uk-table-shrink uk-text-nowrap">Data da submissão</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($prolongamentos as $prolongamento)
                                <tr class="uk-background-muted uk-table-link">
                                    <td class="uk-text-bold uk-table-link uk-text-normal">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ $prolongamento->id }}
                                        </a>
                                    </td>
                                    <td class="uk-text-bold uk-table-link uk-text-normal">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ $prolongamento->user->name }}
                                        </a>
                                    </td>

                                    <td class="uk-text-normal uk-table-link">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ $prolongamento->sector->name }}
                                        </a>
                                    </td>

                                    <td class="uk-table-link uk-text-normal">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ date('d/m/Y', strtotime($prolongamento->dados->data_prolongamento)) }}
                                        </a>
                                    </td>
                                    <td class="uk-text-nowrap uk-table-link uk-text-normal">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ date('H:i', strtotime($prolongamento->dados->hora_inicio_prolongamento)) }}
                                        </a>
                                    </td>

                                    <td class="uk-table-link uk-text-normal">
                                        <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                            {{ date('d/m/Y', strtotime($prolongamento->created_at)) }}
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                @include('layouts.empty')
            @endif
        </div>
    </div>

    @component('layouts.alertDate')
    @endcomponent
    <script src="{{ asset('js/ajax-requests.js') }}" defer></script>

@endsection

resources/views/prolongamento/index.blade.php
@extends('layouts.admin')

@section('title-page')
Prolongamentos
@endsection
@section('links')
Prolongamentos
@endsection
@section('link')
Prolongamentos
@endsection
@section('content-main')
<div class="conntainer">
    @include('layouts.flash')
    <div class="uk-align-right uk-margin-large-right uk-margin-remove-bottom">

        @auth
        @if(Auth::user()->hasRole('gestor-recursos-humanos'))
        <a href="{{ route('prolongamento.all') }}"
            class="uk-margin-large-left uk-button uk-text-normal uk-button-text uk-text-bold"><i
                class="fas fa-list-alt"></i>
            Encontrar prolongamentos</a>
        @endif
        @endauth


        <a href="{{ route('prolongamento.create') }}"
            class="uk-margin-large-left uk-button uk-text-normal uk-button-text uk-text-bold"><i
                class="fas fa-plus-circle"></i> Emitir prolongamento</a>
    </div>
    <div class="uk-section uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
        @if(!$prolongamentos->isEmpty())
        <div class="uk-card uk-card-default uk-width-1-1@s">
            <div class="uk-overflow-auto">
                <table id="avarias-tb"
                    class="uk-table uk-table-hover uk-table-responsive uk-table-middle uk-table-divider">
                    <thead>
                        <tr>
                            <th id="table-header" class="uk-width-small">Referência</th>
                            <th id="table-header" class="uk-width-small">Requisitante</th>
                            <th id="table-header" class="uk-width-small">Sector</th>

                            <th id="table-header" class="uk-width-small">Data</th>
                            <th id="table-header" class="uk-table-shrink uk-text-nowrap">Hora do início</th>
                            <th id="table-header" class="uk-table-shrink uk-text-nowrap">Data da submissão</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($prolongamentos as $prolongamento)
                        <tr class="uk-background-muted uk-table-link">
                            <td class="uk-text-bold uk-table-link uk-text-normal">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ $prolongamento->id }}
                                </a>
                            </td>
                            <td class="uk-text-bold uk-table-link uk-text-normal">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ $prolongamento->user->name }}
                                </a>
                            </td>

                            <td class="uk-text-normal uk-table-link">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ $prolongamento->sector->name }}
                                </a>
                            </td>

                            <td class="uk-table-link uk-text-normal">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ date('d/m/Y', strtotime($prolongamento->dados->data_prolongamento)) }}
                                </a>
                            </td>
                            <td class="uk-text-nowrap uk-table-link uk-text-normal">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ date('H:i', strtotime($prolongamento->dados->hora_inicio_prolongamento)) }}
                                </a>
                            </td>

                            <td class="uk-table-link uk-text-normal">
                                <a class="uk-link-reset" href="{{ route('prolongamento.show', $prolongamento->id) }}">
                                    {{ date('d/m/Y', strtotime($prolongamento->created_at)) }}
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @else
        @include('layouts.empty')
        @endif
    </div>
</div>
@endsection