routes/web.php
    $manager_role->slug = 'gestor-administracao';
    $manager_role->name = 'Gestor Administrativo';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'gestor-manutencao';
    $manager_role->name = 'Gestor da área de manutenção ';
    $manager_role->save();

    $motorista_role = new Role();
    $motorista_role->slug = 'motorista';
    $motorista_role->name = 'Motorista';
    $motorista_role->save();

    $recursos_role = Role::where('slug', 'gestor-recursos-humanos')->first();
    $gestor_administracao_role = Role::where('slug', 'gestor-administracao')->first();
    $usuario_normal_role = Role::where('slug', 'usuario-normal')->first();
    $super_admin_role = Role::where('slug', 'super-admin')->first();
    $manutencao_role = Role::where('slug', 'gestor-manutencao')->first();

    $super_usuario = new User();
    $super_usuario->name = 'Super Usuario';
    $super_usuario->email = 'manager@teste.com';
    $super_usuario->username = 'manage.com';
    $super_usuario->password = bcrypt('manager');
    $super_usuario->save();
    $super_usuario->roles()->attach($super_admin_role);

    $sector = new Sector();
    $sector->user_id = $super_usuario->id;
    $sector->name = "Geral";
    $sector->save();
    $super_usuario->sectors()->attach($sector);

    $administracao = new User();
    $administracao->name = 'Administracao';
    $administracao->email = 'administracao@teste.com';
    $administracao->username = 'administracao.com';
    $administracao->password = bcrypt('administracao');
    $administracao->save();
    $administracao->roles()->attach($gestor_administracao_role);

    $usuario_normal = new User();
    $usuario_normal->name = 'Usuario Normal';
    $usuario_normal->email = 'usuario@teste.com';
    $usuario_normal->username = 'usuario.com';
    $usuario_normal->password = Hash::make(123456);
    $usuario_normal->save();
    $usuario_normal->roles()->attach($usuario_normal_role);

    $recursosH = new User();
    $recursosH->name = 'Recursos H';
    $recursosH->email = 'recursosh@teste.com';
    $recursosH->username = 'recursosh.com';
    $recursosH->password = Hash::make(123456);
    $recursosH->save();
    $recursosH->roles()->attach($recursos_role);

    $manutencao = new User();
    $manutencao->name = 'Manutencao';
    $manutencao->email = 'manutencao@teste.com';
    $manutencao->username = 'manutencao.com';
    $manutencao->password = Hash::make(123456);
    $manutencao->save();
    $manutencao->roles()->attach($manutencao_role);

    return User::all();

});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', function () {
        auth()->logout();
        Session()->flush();
        return Redirect::to('/');
    })->name('logout');

    Route::get('/', 'HomeController@index')->name('normal.dashboard');
    Route::resource('avaria', 'AvariaController');
    Route::resource('escala', 'EscalaController');
    Route::resource('remuneracao', 'AumentoRemuneracaoController');
    Route::resource('justificacao', 'JustificaoFaltaController');
    Route::resource('prolongamento', 'ProlongamentoController');
    Route::resource('pedido', 'PedidoController');
    Route::resource('pedidoRescisao', 'PedidoRescisaoController');
    Route::get('avaria/{avaria}/resposta/detalhes', 'AvariaController@showResponse')->name('avaria.resposta-detalhes');
    Route::get('avaria/{avaria}/pdf/', 'AvariaController@exportAvariaPdf')->name('avaria.export');
    Route::resource('requisicaoTransporte', 'RequisicaoTransporteController');
    Route::get('carta/create', 'CartaController@create')->name('carta.create');

    Route::resource('advertencia', 'AdvertenciaController');
    Route::get('advertencia/geraPDF/{advertencia}', 'AdvertenciaController@makePDF')->name('advertencia.PDF');

    Route::put('avaria/{avaria}/responder', 'AvariaController@responderSolicitacao')->name('avaria.response');

    Route::put('avaria/{avaria}/feedback', 'AvariaController@feedback')->name('avaria.feedback');

    Route::put('avaria/{avaria}/estado', 'AvariaController@setEstado')->name('avaria.estado');

    Route::post('/fecth/dependent', 'RequisicaoTransporteController@selectViagem')->name('requisicao.selectViagem');

    Route::get('/substituicao', 'FeriaController@substituicoes')->name('feria.subistacao');

    Route::get('avaria/geraPDF/{avaria}', 'AvariaController@geraPDF')->name('avaria-requisicao.geraPDF');

    Route::get('pre_requisicao/PDF/{pre}', 'RequisicaoTransporteController@exportPreReqPdf')->name('pre-requisicao.PDF');

    Route::resource('preRequest', 'PreRequisicaoController');
    Route::get('preRequest/{pre}/read', 'PreRequisicaoController@read')->name('pre.read');

    Route::get('user/details/{user}', 'UserRegisterController@show')->name('user.details');
    Route::put('password/update', 'UserRegisterController@updatePassword')->name('password.update');

    Route::post('getSector', 'SectorController@getSector')->name('sector.getSector');
    Route::post('getUser', 'UserRegisterController@getUser')->name('user.getUser');
    Route::post('getTecnico', 'TecnicoController@getTecnico')->name('tecnico.getTecnico');
    Route::post('getMotorista', 'MotoristaController@getMotorista')->name('motorista.getMotorista');
    Route::post('getTransporte', 'TransporteController@getTransporte')->name('transporte.getTransporte');
    Route::resource('rescisao', 'RescisaoController');
    Route::resource('feria', 'FeriaController');
    Route::post('carta/store', 'CartaController@store')->name('carta.store');
    Route::get('carta', 'CartaController@index')->name('carta.index');
    Route::get('chefe/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer.chefe');

});

//Manutencao
Route::group(['middleware' => 'role:gestor-manutencao'], function () {
    Route::resource('tecnico', 'TecnicoController');
    Route::resource('fornecedor', 'FornecedorController');
    Route::post('getFornecedor', 'FornecedorController@getFornecedor');
    Route::get('avaria/{avaria}/descricao', 'AvariaController@showAvariaRequest')->name('avaria.descricao');
    Route::get('avarias/todas', 'AvariaController@todasAvarias')->name('avaria.todas');
    Route::get('avarias/report', 'AvariaController@report')->name('avaria.report');
});

//Manutencao
Route::group(['middleware' => 'role:motorista'], function () {
    Route::resource('tarefa', 'TarefaController');
});

// Administrativo
Route::group(['middleware' => 'role:gestor-administracao'], function () {
    Route::resource('transportes', 'TransporteController');
    Route::resource('local', 'LocalController');
    Route::resource('motorista', 'MotoristaController');
    Route::get('requisicoes', 'RequisicaoTransporteController@allRequests')->name('requisicaoTransporte.all');

    Route::get('requisicoes/report', 'RequisicaoTransporteController@report')->name('requisicoes.report');

    Route::get('requisicao/pdf/{pre}', 'RequisicaoTransporteController@gerarPDF')->name('requisicao.export');
});

//Recursos Humanos
Route::group(['middleware' => 'role:gestor-recursos-humanos'], function () {
    Route::get('cartas/search', 'CartaController@search');
    Route::resource('contrato', 'ContratoController');
    Route::resource('adenda', 'AdendaController');
    Route::get('rechumanos/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer');
    Route::get('adenda/{adenda}/pdf', 'AdendaController@makePDF')->name('adenda.pdf');
    Route::get('contratos/search', 'ContratoController@search');
    Route::get('contratos/{contrato}/pdf', 'ContratoController@makePDFIndividual')->name('contrato.pdfNormal');
    Route::get('prolongamento/{contrato}/pdf', 'ProlongamentoController@makePDF')->name('prolongamento.pdf');
    Route::get('escala/{escala}/pdf', 'EscalaController@makePDF')->name('escala.pdf');
    Route::get('contrato/create/cps', 'ContratoController@createCps')->name('contrato.createCps');
    Route::get('prolongamentos/all', 'ProlongamentoController@todosProlongamentos')->name('prolongamento.all');
    Route::get('ferias/all', 'FeriaController@todasFerias')->name('feria.all');
    Route::get('justificacoes/all', 'JustificaoFaltaController@todasJustificacoes')->name('justificacao.all');

    Route::get('advertencias/all', 'AdvertenciaController@all')->name('advertencia.all');


    Route::get('escalas/all', 'EscalaController@todasEscalas')->name('escala.all');
    Route::get('remuneracoes/all', 'AumentoRemuneracaoController@todas')->name('remuneracao.all');
    Route::get('contratos/all', 'ContratoController@todos')->name('contrato.all');
    Route::get('pedidosRescisao/all', 'PedidoRescisaoController@todos')->name('pedidoRescisao.all');

    Route::get('contrato/{id}/user', 'ContratoController@contratoPeloUsuario')->name('contrato.user');

    Route::get('escalas/report', 'EscalaController@report')->name('escala.report');
    Route::get('pedidosRescisao/report', 'PedidoRescisaoController@report')->name('pedidoRescisao.report');

    Route::get('prolongamentos/report', 'ProlongamentoController@report')->name('prolongamento.report');

    Route::get('justificacoes/report', 'JustificaoFaltaController@report')->name('prolongamento.report');

    Route::get('remuneracoes/report', 'AumentoRemuneracaoController@report')->name('remuneracoes.report');


});

Route::group(['middleware' => 'super-admin'], function () {

    Route::get('/registar', 'UserRegisterController@registerForm')->name('user.register');
    Route::post('/registar', 'UserRegisterController@create')->name('user.gravar');
    Route::resource('sector', 'SectorController');
    Route::get('/usuarios', 'UserRegisterController@index')->name('user.all');
    Route::get('/usuarios/{user}/edit', 'UserRegisterController@edit')->name('user.edit');
    Route::put('/usuarios/{user}/update', 'UserRegisterController@update')->name('user.actualizar');

app/Local.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Local extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'name', 'designacao', 'endereco', 'is_active'
    ];
}

app/Http/Controllers/LocalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LocalRequest;
use App\Local;
use Illuminate\Http\Request;

class LocalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $locais = Local::where('is_active', 1)->get();
        return view('local.index')->with('locais', $locais);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('local.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LocalRequest $request)
    {
        Local::create($request->all());
        return redirect(route('local.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Local  $local
     * @return \Illuminate\Http\Response
     */
    public function show(Local $local)
    {
        $designacoes = array('Local', 'Nacional', 'Internacional');
        return view('local.edit', compact(['local', 'designacoes']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Local  $local
     * @return \Illuminate\Http\Response
     */
    public function edit(Local $local)
    {
        return $local;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Local  $local
     * @return \Illuminate\Http\Response
     */
    public function update(LocalRequest $request, Local $local)
    {
        Local::where('id', '=', $local->id)->update($request->except(['_token', '_method']));
        return redirect(route('local.index'))->with('info', 'Detalhes de '. $local->name.' actualizados com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Local  $local
     * @return \Illuminate\Http\Response
     */
    public function destroy(Local $local)
    {
        //
    }
}

resources/views/local/create.blade.php
@extends('layouts.admin')

@section('title-page')
Registro de Local
@endsection
@section('links')
<a href="{{ route('local.index') }}" class="uk-button uk-button-text">Locais</a> / Registro
@endsection
@section('link')
Registro de Local
@endsection
@section('content-main')
<div class="conntainer">
    @include('layouts.flash')
    <div class="uk-section uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
        <div class="uk-card uk-card-default uk-width-1-1@s">
            <form id="form_motorista" method="POST" action="{{ route('local.store') }}"
            class="uk-form-stacked">
            {{ csrf_field() }}
                <div class="uk-card-body uk-margin  uk-grid">

                    <div class="uk-width-1-3@s">
                        <label for="name" class="uk-form-label">
                            {{ __('Nome') }}
                        </label>
                        <div class="uk-form-control">
                            <input class="uk-input @error('name') uk-form-danger @enderror" id="name" name="name" type="text"
                                value="{{ old('name') }}" required
                                   placeholder="Nome do local"
                                    autofocus>
                            @error('name')
                            <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="uk-width-1-3@s">
                        <label for="endereco" class="uk-form-label">
                            {{ __('Endereço') }}
                        </label>
                        <input id="endereco" type="text" class="uk-input @error('endereco') uk-form-danger @enderror" name="endereco"
                        placeholder="Endereço do local"
                            value="{{ old('endereco') }}" autocomplete="endereco">
                        @error('endereco')
                        <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="uk-width-1-3@s">
                        <label for="designacao" class="uk-form-label">
                            {{ __('Designação') }}
                        </label>
                        <div class="uk-form-control">
                            <select id="designacao" name="designacao" class="uk-select @error('designacao') uk-form-danger @enderror">
                                <option selected disabled>Seleccione a designação</option>
                                <option value="Local">Local</option>
                                <option value="Nacional">Nacional</option>
                                <option value="Internacional">Internacional</option>
                            </select>
                            @error('designacao')
                            <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                </div>
                <div class="uk-form-control uk-card-footer">
                    <button type="submit" class="uk-button uk-align-right uk-border-rounded uk-button-secondary">
                        {{ __('Registar local') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/local/details.blade.php
@extends('layouts.admin')

@section('title-page')
    Dados do Motorista
@endsection
@section('links')
    <a href="{{ route('motorista.index') }}" class="uk-button uk-button-text">Motoristas</a> / Detalhes
@endsection
@section('link')
    Dados do Motorista
@endsection
@section('content-main')
    <div class="conntainer">
        @include('layouts.flash')
        <div class="uk-section uk-padding uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
            <div class="uk-card uk-card-default uk-width-1-1@s">
                <div class="uk-card-body uk-margin  uk-grid">
                    <div class="uk-width-1-1@s">
                        <div>
                            <p class="uk-align-right">
                                <a
                                    href="{{ route('motorista.edit', $motorista->id) }}"
                                    class="uk-button  uk-border-rounded uk-text-bold text-white btn-warning">Editar</a>
                                <button uk-toggle="target: #my-id" type="button"
                                        class="uk-button uk-button-danger uk-text-bold uk-border-rounded">
                                    Apagar
                                </button>
                            </p>
                        </div>
                    </div>

                    <div class="uk-width-1-2@s">
                        <label for="name" class="uk-form-label">
                            {{ __('Nome completo') }}
                        </label>
                        <div class="uk-form-control">
                            <div class="uk-placeholder">
                                {{ $motorista->name }} {{ $motorista->surname }}
                            </div>
                        </div>
                    </div>
                    <div class="uk-width-1-4@s">
                        <label for="gender" class="uk-form-label">
                            {{ __('Sexo') }}
                        </label>
                        <div class="uk-form-control">
                            <div class="uk-form-control">
                                <div class="uk-placeholder">
                                    {{ $motorista->gender }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="uk-width-1-4@s">
                        <label class="uk-form-label">
                            {{ __('Morada') }}
                        </label>
                        <div class="uk-placeholder uk-margin-remove">
                            {{ $motorista->address }}
                        </div>
                    </div>

                    <div class="uk-width-1-3@s">
                        <label for="area" class="uk-form-label">
                            {{ __('Número da carta de Condução') }}
                        </label>
                        <div class="uk-form-control">
                            <div class="uk-placeholder">
                                {{ $motorista->licence_number?? '_________________' }}
                            </div>
                        </div>
                    </div>
                    <div class="uk-width-1-3@s">
                        <label for="telefone" class="uk-form-label">
                            {{ __('Telefone') }}
                        </label>
                        <div class="uk-form-control">
                            <div class="uk-placeholder">
                                {{ $motorista->phone }}
                            </div>
                        </div>
                    </div>
                    <div class="uk-width-1-3@s">
                        <label class="uk-form-label">
                            {{ __('Situação actual') }}
                        </label>
                        <div class="uk-placeholder uk-margin-remove">
                            {{ $motorista->is_active? 'Motorista': 'Ex Motorista' }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @component('layouts.delete-alert')
        @slot('model_title')
            O(A) motorista(a)
        @endslot
        @slot('info_title')
            {{ $motorista->name }}
        @endslot
        @slot('slot')

            <form class="uk-inline" method="POST" action="{{ route('motorista.destroy', $motorista) }}">
                @method('DELETE')
                @csrf
                <button
                    class="uk-button uk-button-danger uk-border-rounded uk-box-shadow-hover-small">Remover
                </button>
            </form>

        @endslot
    @endcomponent
@endsection

resources/views/local/edit.blade.php
@extends('layouts.admin')

@section('title-page')
Editar dados do Local
@endsection
@section('links')
<a href="{{ route('local.index') }}" class="uk-button uk-button-text">Locais</a> / Actualização
@endsection
@section('link')
Editar dados do Local
@endsection
@section('content-main')
<div class="conntainer">
    @include('layouts.flash')
    <div class="uk-section uk-padding uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
        <div class="uk-card uk-card-default uk-width-1-1@s">
            <form method="POST" action="{{ route('local.update', $local->id) }}"
            class="uk-form-stacked">
            @method('PUT')
            {{ csrf_field() }}
                <div class="uk-card-body uk-margin  uk-grid">
                    <div class="uk-width-1-2@s uk-margin">
                        <label for="name" class="uk-form-label">
                            {{ __('Primeiros nomes') }}
                        </label>
                        <div class="uk-form-control">
                            <input class="uk-input @error('name') uk-form-danger @enderror" id="name" name="name" type="text"
                                value="{{ $local->name }}" required autocomplete="name" autofocus>
                            @error('name')
                            <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="uk-width-1-2@s">
                        <label for="endereco" class="uk-form-label">
                            {{ __('Endereço') }}
                        </label>
                        <div class="uk-form-control">
                            <input class="uk-input @error('endereco') uk-form-danger @enderror" id="endereco" name="endereco"
                                type="text" value="{{ $local->endereco }}" required autocomplete="endereco" autofocus>
                            @error('endereco')
                            <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="uk-width-1-2@s">
                        <label for="designacao" class="uk-form-label">
                            {{ __('Designação') }}
                        </label>
                        <div class="uk-form-control">
                            <select class="uk-select @error('designacao') uk-form-danger @enderror" id="designacao" name="designacao">
                                @foreach($designacoes as $designacao)
                                <option value="{{ $designacao }}" {{ $designacao== $local->designacao? 'selected':'' }}>
                                    {{ $designacao }}</option>
                                @endforeach
                            </select>

                            @error('designacao')
                            <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                </div>
                <div class="uk-form-control uk-card-footer">
                    <button type="submit" class="uk-button uk-align-right uk-border-rounded uk-button-primary">
                        {{ __('Actualizar dados do local') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/local/index.blade.php
@extends('layouts.admin')

@section('title-page')
    Lista de locais
@endsection
@section('links')
    Lista de locais
@endsection
@section('link')
    Lista de locais
@endsection
@section('content-main')
    <div class="conntainer">
        @include('layouts.flash')
        <div class="uk-align-right uk-margin-large-right uk-margin-remove-bottom">
            <a href="{{ route('local.create') }}"
               class="uk-margin-large-left uk-button uk-text-normal uk-button-text uk-text-bold"><i
                    class="fas fa-plus-circle"></i> Registar local</a>
        </div>
        <div class="uk-section uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
            @if(!$locais->isEmpty())
                <div class="uk-card uk-card-default uk-width-1-1@s">
                    <div class="uk-overflow-auto">
                        <table id="avarias-tb" class="uk-table uk-table-hover uk-table-middle uk-table-divider">
                            <thead>
                            <tr>
                                <th id="table-header" class="uk-table-shrink uk-text-nowrap">Nome</th>
                                <th id="table-header" class="uk-table-shrink uk-text-nowrap">Endereço</th>
                                <th id="table-header" class="uk-width-small uk-text-nowrap">Designação</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($locais as $local)
                                <tr class="uk-background-muted">
                                    <td class="uk-text-bold  uk-table-link uk-text-normal uk-text-nowrap">
                                        <a class="uk-link-reset" href="{{route('local.show', $local)}}">
                                        {{ $local->name }}
                                        </a>
                                    </td>
                                    <td class="uk-table-link  uk-table-link  uk-text-normal">
                                        <a class="uk-link-reset" href="{{route('local.show', $local)}}">{{ $local->endereco }}</a>
                                    </td>
                                    <td class="uk-text-truncate  uk-table-link  uk-text-normal">
                                        <a class="uk-link-reset" href="{{route('local.show', $local)}}">
                                        {{ $local->designacao }}
                                        </a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                @include('layouts.empty')
            @endif
        </div>
    </div>
@endsection