routes/web.php
    $recurosHumanos = new Role();
    $recurosHumanos->slug = 'gestor-recursos-humanos';
    $recurosHumanos->name = 'Gestor de Recursos Humanos';
    $recurosHumanos->save();

    $manager_role = new Role();
    $manager_role->slug = 'super-admin';
    $manager_role->name = 'Super Admim';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'usuario-normal';
    $manager_role->name = 'Usuário normal ';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'gestor-administracao';
    $manager_role->name = 'Gestor Administrativo';
    $manager_role->save();

    $manager_role = new Role();
    $manager_role->slug = 'gestor-manutencao';
    $manager_role->name = 'Gestor da área de manutenção ';
    $manager_role->save();

    $motorista_role = new Role();
    $motorista_role->slug = 'motorista';
    $motorista_role->name = 'Motorista';
    $motorista_role->save();

    $recursos_role = Role::where('slug', 'gestor-recursos-humanos')->first();
    $gestor_administracao_role = Role::where('slug', 'gestor-administracao')->first();
    $usuario_normal_role = Role::where('slug', 'usuario-normal')->first();
    $super_admin_role = Role::where('slug', 'super-admin')->first();
    $manutencao_role = Role::where('slug', 'gestor-manutencao')->first();

    $super_usuario = new User();
    $super_usuario->name = 'Super Usuario';
    $super_usuario->email = 'manager@teste.com';
    $super_usuario->username = 'manage.com';
    $super_usuario->password = bcrypt('manager');
    $super_usuario->save();
    $super_usuario->roles()->attach($super_admin_role);

    $sector = new Sector();
    $sector->user_id = $super_usuario->id;
    $sector->name = "Geral";
    $sector->save();
    $super_usuario->sectors()->attach($sector);

    $administracao = new User();
    $administracao->name = 'Administracao';
    $administracao->email = 'administracao@teste.com';
    $administracao->username = 'administracao.com';
    $administracao->password = bcrypt('administracao');
    $administracao->save();
    $administracao->roles()->attach($gestor_administracao_role);

    $usuario_normal = new User();
    $usuario_normal->name = 'Usuario Normal';
    $usuario_normal->email = 'usuario@teste.com';
    $usuario_normal->username = 'usuario.com';
    $usuario_normal->password = Hash::make(123456);
    $usuario_normal->save();
    $usuario_normal->roles()->attach($usuario_normal_role);

    $recursosH = new User();
    $recursosH->name = 'Recursos H';
    $recursosH->email = 'recursosh@teste.com';
    $recursosH->username = 'recursosh.com';
    $recursosH->password = Hash::make(123456);
    $recursosH->save();
    $recursosH->roles()->attach($recursos_role);

    $manutencao = new User();
    $manutencao->name = 'Manutencao';
    $manutencao->email = 'manutencao@teste.com';
    $manutencao->username = 'manutencao.com';
    $manutencao->password = Hash::make(123456);
    $manutencao->save();
    $manutencao->roles()->attach($manutencao_role);

    return User::all();

});

Route::group(['middleware' => 'auth'], function () {
    Route::get('logout', function () {
        auth()->logout();
        Session()->flush();
        return Redirect::to('/');
    })->name('logout');

    Route::get('/', 'HomeController@index')->name('normal.dashboard');
    Route::resource('avaria', 'AvariaController');
    Route::resource('escala', 'EscalaController');
    Route::resource('remuneracao', 'AumentoRemuneracaoController');
    Route::resource('justificacao', 'JustificaoFaltaController');
    Route::resource('prolongamento', 'ProlongamentoController');
    Route::resource('pedido', 'PedidoController');
    Route::resource('pedidoRescisao', 'PedidoRescisaoController');
    Route::get('avaria/{avaria}/resposta/detalhes', 'AvariaController@showResponse')->name('avaria.resposta-detalhes');
    Route::get('avaria/{avaria}/pdf/', 'AvariaController@exportAvariaPdf')->name('avaria.export');
    Route::resource('requisicaoTransporte', 'RequisicaoTransporteController');
    Route::get('carta/create', 'CartaController@create')->name('carta.create');

    Route::resource('advertencia', 'AdvertenciaController');
    Route::get('advertencia/geraPDF/{advertencia}', 'AdvertenciaController@makePDF')->name('advertencia.PDF');

    Route::put('avaria/{avaria}/responder', 'AvariaController@responderSolicitacao')->name('avaria.response');

    Route::put('avaria/{avaria}/feedback', 'AvariaController@feedback')->name('avaria.feedback');

    Route::put('avaria/{avaria}/estado', 'AvariaController@setEstado')->name('avaria.estado');

    Route::post('/fecth/dependent', 'RequisicaoTransporteController@selectViagem')->name('requisicao.selectViagem');

    Route::get('/substituicao', 'FeriaController@substituicoes')->name('feria.subistacao');

    Route::get('avaria/geraPDF/{avaria}', 'AvariaController@geraPDF')->name('avaria-requisicao.geraPDF');

    Route::get('pre_requisicao/PDF/{pre}', 'RequisicaoTransporteController@exportPreReqPdf')->name('pre-requisicao.PDF');

    Route::resource('preRequest', 'PreRequisicaoController');
    Route::get('preRequest/{pre}/read', 'PreRequisicaoController@read')->name('pre.read');

    Route::get('user/details/{user}', 'UserRegisterController@show')->name('user.details');
    Route::put('password/update', 'UserRegisterController@updatePassword')->name('password.update');

    Route::post('getSector', 'SectorController@getSector')->name('sector.getSector');
    Route::post('getUser', 'UserRegisterController@getUser')->name('user.getUser');
    Route::post('getTecnico', 'TecnicoController@getTecnico')->name('tecnico.getTecnico');
    Route::post('getMotorista', 'MotoristaController@getMotorista')->name('motorista.getMotorista');
    Route::post('getTransporte', 'TransporteController@getTransporte')->name('transporte.getTransporte');
    Route::resource('rescisao', 'RescisaoController');
    Route::resource('feria', 'FeriaController');
    Route::post('carta/store', 'CartaController@store')->name('carta.store');
    Route::get('carta', 'CartaController@index')->name('carta.index');
    Route::get('chefe/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer.chefe');

});

//Manutencao
Route::group(['middleware' => 'role:gestor-manutencao'], function () {
    Route::resource('tecnico', 'TecnicoController');
    Route::resource('fornecedor', 'FornecedorController');
    Route::post('getFornecedor', 'FornecedorController@getFornecedor');
    Route::get('avaria/{avaria}/descricao', 'AvariaController@showAvariaRequest')->name('avaria.descricao');
    Route::get('avarias/todas', 'AvariaController@todasAvarias')->name('avaria.todas');
    Route::get('avarias/report', 'AvariaController@report')->name('avaria.report');
});

//Manutencao
Route::group(['middleware' => 'role:motorista'], function () {
    Route::resource('tarefa', 'TarefaController');
});

// Administrativo
Route::group(['middleware' => 'role:gestor-administracao'], function () {
    Route::resource('transportes', 'TransporteController');
    Route::resource('local', 'LocalController');
    Route::resource('motorista', 'MotoristaController');
    Route::get('requisicoes', 'RequisicaoTransporteController@allRequests')->name('requisicaoTransporte.all');

    Route::get('requisicoes/report', 'RequisicaoTransporteController@report')->name('requisicoes.report');

    Route::get('requisicao/pdf/{pre}', 'RequisicaoTransporteController@gerarPDF')->name('requisicao.export');
});

//Recursos Humanos
Route::group(['middleware' => 'role:gestor-recursos-humanos'], function () {
    Route::get('cartas/search', 'CartaController@search');
    Route::resource('contrato', 'ContratoController');
    Route::resource('adenda', 'AdendaController');
    Route::get('rechumanos/parecer/{justificacao}', 'JustificaoFaltaController@parecer')->name('justificacao.parecer');
    Route::get('adenda/{adenda}/pdf', 'AdendaController@makePDF')->name('adenda.pdf');
    Route::get('contratos/search', 'ContratoController@search');
    Route::get('contratos/{contrato}/pdf', 'ContratoController@makePDFIndividual')->name('contrato.pdfNormal');
    Route::get('prolongamento/{contrato}/pdf', 'ProlongamentoController@makePDF')->name('prolongamento.pdf');
    Route::get('escala/{escala}/pdf', 'EscalaController@makePDF')->name('escala.pdf');
    Route::get('contrato/create/cps', 'ContratoController@createCps')->name('contrato.createCps');
    Route::get('prolongamentos/all', 'ProlongamentoController@todosProlongamentos')->name('prolongamento.all');
    Route::get('ferias/all', 'FeriaController@todasFerias')->name('feria.all');
    Route::get('justificacoes/all', 'JustificaoFaltaController@todasJustificacoes')->name('justificacao.all');

    Route::get('advertencias/all', 'AdvertenciaController@all')->name('advertencia.all');


    Route::get('escalas/all', 'EscalaController@todasEscalas')->name('escala.all');
    Route::get('remuneracoes/all', 'AumentoRemuneracaoController@todas')->name('remuneracao.all');
    Route::get('contratos/all', 'ContratoController@todos')->name('contrato.all');
    Route::get('pedidosRescisao/all', 'PedidoRescisaoController@todos')->name('pedidoRescisao.all');

    Route::get('contrato/{id}/user', 'ContratoController@contratoPeloUsuario')->name('contrato.user');

    Route::get('escalas/report', 'EscalaController@report')->name('escala.report');
    Route::get('pedidosRescisao/report', 'PedidoRescisaoController@report')->name('pedidoRescisao.report');

    Route::get('prolongamentos/report', 'ProlongamentoController@report')->name('prolongamento.report');

    Route::get('justificacoes/report', 'JustificaoFaltaController@report')->name('prolongamento.report');

    Route::get('remuneracoes/report', 'AumentoRemuneracaoController@report')->name('remuneracoes.report');


});

Route::group(['middleware' => 'super-admin'], function () {

app/Avaria.php
<?php

namespace App;

use App\Material;
use Illuminate\Database\Eloquent\Model;

class Avaria extends Model
{
    public $incrementing = false;
    protected $fillable = [
        'descricao', 'sector_id', 'data_para_resolucao', 'user_id', 'plano_reparacao', 'localizacao',
        'plano_prevencao', 'estado', 'prioridade' , 'natureza', 'diagnostico', 'mao_obra_inicial',
        'mao_obra_final', 'proximo_passo', 'hora_para_resolucao', 'compartimento', 'comprovativo',
        'horas_duracao', 'minutos_duracao', 'referencia',
        'fornecedor_servico', 'responsavel', 'foi_lida', 'garantia', 'valor_total' , 'custo_do_material', 'tempo_prioridade', 'forma_pagamento', 'observacao'
    ];

    public function sector()
    {
        return $this->belongsTo(Sector::class);
    }

    public function materiais()
    {
        return $this->hasMany(Material::class);
    }

    public function anotacoes()
    {
        return $this->hasMany(AnotacoesAvaria::class);
    }

   public function resposta()
    {
        return $this->hasOne(ManutencaoResposta::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

resources/views/avarias/data-export.blade.php
@extends('layouts.admin')

@section('title-page')
    Todas avarias
@endsection
@section('links')
    <a class="uk-button uk-button-text" href="{{route('avaria.index')}}">Avarias</a> / Todas
@endsection
@section('link')
    Todas avarias
@endsection
@section('content-main')
    <div class="conntainer">
        @include('layouts.flash')
        <div class="uk-align-right uk-margin-large-right uk-margin-remove-bottom">
            <a href="{{ route('avaria.create') }}"
               class="uk-margin-large-left uk-button uk-text-normal uk-button-text uk-text-bold"><i
                    class="fas fa-plus-circle"></i> Registar avaria</a>
        </div>
        @if(Auth::check() && !Auth::user()->hasRole('gestor-manutencao') && !$avarias)

            <p class="uk-margin-medium-left">
                Simbolos
                <br>
                &ensp;<i class="fas fa-clipboard"></i> Resposta da avaria</p>

        @endif


        <div class="uk-section uk-padding-small uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
            @if(!$avarias->isEmpty())
                <div class="uk-card uk-card-default uk-width-1-1@s">
                    <div class="uk-overflow-auto">
                        <table id="tableDatatableAvarias"
                               class="uk-table uk-table-hover uk-table-responsive uk-table-middle uk-table-divider">
                            <thead>
                            <tr>
                                <th id="table-header" class="uk-text-small uk-text-nowrap uk-table-shrink">Código</th>
                                <th id="table-header" class="uk-text-small uk-table-shrink uk-text-nowrap">Est. avaria
                                </th>
                                <th id="table-header" class="uk-text-small uk-width-small">Data de solicitação</th>
                                <th id="table-header" class="uk-text-small uk-table-shrink">Sector</th>
                                <th id="table-header" class="uk-text-small uk-text-nowrap uk-table-shrink">Est.
                                    solicitação
                                </th>
                                <th id="table-header" class="uk-text-small uk-text-nowrap uk-table-shrink">Prioridade
                                </th>
                                <th id="table-header" class="uk-text-small uk-text-nowrap uk-table-shrink">Resposta
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($avarias as $avaria)
                                <tr class="uk-background-muted {{ $avaria->prioridade == 'média'? 'table-warning': ($avaria->prioridade == 'alta'? ('table-danger'):'table-light') }} uk-background-blend-multiply">
                                    <td class="uk-text-bold uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.show', $avaria)}}">
                                            {{ $avaria->id }}
                                        </a>
                                    </td>
                                    <td class="uk-text-truncate uk-table-link uk-text-bold">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.show', $avaria)}}"> {{ ucfirst($avaria->estado) }} </a>
                                    </td>
                                    <td class="uk-text-nowrap uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.show', $avaria)}}">
                                            {{ date( 'd / m / Y' , strtotime($avaria->created_at)) }}
                                            às {{ date( 'H:i' , strtotime($avaria->created_at)) }}
                                        </a>
                                    </td>
                                    <td class="uk-text-nowrap uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.show', $avaria)}}">
                                            {{ $avaria->sector->name }}
                                        </a>
                                    </td>
                                    <td class="uk-text-nowrap uk-text-bold uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.show', $avaria)}}">
                                            {{ ucfirst($avaria->foi_lida) }}
                                        </a>
                                    </td>
                                    <td class="uk-text-nowrap  uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.resposta-detalhes', $avaria)}}">
                                            {{ ucfirst($avaria->prioridade) }}
                                        </a>
                                    </td>
                                    <td class="uk-text-nowrap uk-text-small uk-text-bold uk-table-link">
                                        <a class="uk-link-reset"
                                           href="{{route('avaria.resposta-detalhes', $avaria)}}">
                                            {{ $avaria->resposta == NULL? 'Sem resposta': 'Com Resposta'  }}
                                        </a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                @include('layouts.empty')
            @endif
        </div>
    </div>
    @component('layouts.alertDate')
    @endcomponent
@endsection

resources/views/avarias/resposta-details.blade.php
@extends('layouts.admin')

@section('title-page')
    Resposta do sector de manutenção
@endsection
@section('links')
    <a class="uk-button uk-button-text" href="{{ route('avaria.index') }}">Avarias</a> / Resposta
@endsection
@section('link')
    Resposta do sector de manutenção
@endsection
@section('content-main')
    <div class="conntainer">
        @include('layouts.flash')
        @if($avaria->resposta != NULL)

            <div class="uk-section uk-section-small uk-flex uk-flex-center uk-width-1-1@s">
                <div class="uk-card uk-card-default uk-width-1-1@s">
                    <div class="uk-card-badge uk-label">{{ $avaria->estado }}</div>
                    <div class="uk-card-body uk-margin uk-grid">
                        <div class="uk-width-1-1 uk-margin-medium-bottom">
                            <a href="{{ $avaria->estado == "concluido"? route('avaria.show', $avaria->id): route('avaria.edit', $avaria->id) }}"
                               class="uk-button uk-button-secondary uk-text-bolder uk-border-rounded uk-box-shadow-hover-large uk-align-right">
                                ir para a avaria <i class="fas fa-long-arrow-alt-right"></i>
                            </a>
                            <p class="uk-h4 uk-text-muted uk-text-normal"><span
                                    class="uk-text-bold uk-text-small uk-text-primary">Referência</span><br>{{ $avaria->id }}
                            </p>

                            <p class="uk-h4 uk-text-muted uk-text-normal"><span
                                    class="uk-text-bold uk-text-small uk-text-primary">Progresso da avaria</span><br>{{ ucfirst($avaria->estado) }}
                            </p>
                        </div>

                        <div class="uk-width-1-2@s">
                            <div class=" uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Observação do gestor') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ $avaria->resposta->observacao?? '_____________________' }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-4@s">
                            <div class="uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Remetente') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ $avaria->user->name }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-4@s">
                            <div class="uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Resposta de:') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ $avaria->resposta->user->name }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-3@s uk-margin-small-top">
                            <div class=" uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Responsável pela resolução') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ $avaria->responsavel }}</p>
                            </div>
                        </div>
                        <div class="uk-width-1-3@s uk-margin-small-top">
                            <div class=" uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Responsável pela resolução') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ $avaria->resposta->tecnico->phone }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-4@s uk-margin-small-top">
                            <div class="uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Data para resolução') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ date('d/m/Y', strtotime($avaria->data_para_resolucao)) }}
                                    às {{ date('H:i', strtotime($avaria->hora_para_resolucao)) }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-4@s uk-margin-top">

                            <div class="uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('O seu parecer') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ ucfirst($avaria->estado_requisitante) }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-4@s uk-margin">

                            <div class="uk-placeholder">
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Respondida a:') }}
                                </label>
                                <p class="uk-text-normal uk-margin-remove-top">{{ date('d/m/Y', strtotime($avaria->resposta->created_at)) }}
                                    às {{ date('H:i', strtotime($avaria->hora_para_resolucao)) }}</p>
                            </div>
                        </div>

                        <div class="uk-width-1-1@s uk-margin-medium-left uk-placeholder">
                            <p class="uk-text-bold uk-h4">Informações sobre a resolução</p>
                            @if($avaria->fornecedor_servico)
                                <p class="uk-text-normal  uk-text-italic">Fornecedor de serviço defenido</p>
                            @endif

                            @if(count($avaria->materiais)>0)

                                <p class="uk-text-normal uk-text-italic">Material necessário já defenido</p>
                            @endif

                            @if($avaria->diagnostico)
                                <p class="uk-text-normal uk-text-italic">Diagnóstico disponível</p>
                            @endif

                            @if($avaria->plano_reparacao)
                                <p class="uk-text-normal uk-text-italic">Plano de reparação defenido</p>
                            @endif

                            @if($avaria->estado)
                                <p class="uk-text-normal uk-text-italic">A avaria está em estado de {{ ucfirst($avaria->estado)}}</p>
                            @endif
                        </div>

                        @if($avaria->estado == 'concluido' and $avaria->estado_requisitante != 'concluida')
                            <form method="POST" action="{{route('avaria.feedback', $avaria)}}" class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                                @method('PUT')
                                @csrf
                                <label for="diagnostico" class="uk-form-label">
                                    {{ __('Confirma que a resolução da avaria já está concluída?') }}
                                </label>
                                <label class="uk-text-small">
                                    <input class="uk-radio" type="radio" id="estado_requisitante"
                                           name="estado_requisitante"
                                           {{ $avaria->estado_requisitante=="não concluida"? "checked": "" }}
                                           value="não concluida"> Não</label>

                                <label class="uk-text-small">
                                    <input class="uk-radio" type="radio" id="estado_requisitante"
                                           {{ $avaria->estado=="concluida"? "checked": "" }}
                                           name="estado_requisitante"
                                           value="concluida"> Sim</label>
                                @error('estado_requisitante')
                                <span class="uk-text-danger uk-text-small">{{ $message }}</span>
                                @enderror

                                <button type="submit" class="uk-button uk-button-small uk-button-primary uk-margin-left uk-border-rounded uk-box-shadow-hover-large" >Submeter</button>
                            </form>

                        @endif

                    </div>
                </div>
            </div>
        @else
            @component('layouts.empty')
                @slot('title')
                    A requisição para resolução da avaria ainda não foi respondida
                @endslot
            @endcomponent
        @endif
    </div>
@endsection